### ISSUE TITLE
Problem creating namespaces

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/nem-ledger-app#3]
Edit: This issue is meant for NIS1, not Symbol 

Sometimes when I'm trying to create a namespace/subnamespace/mosaic the ledger is incorrectly attaching a root namespace that it shouldn't be. 

Here is an example 

<img width="750" alt="image" src="https://user-images.githubusercontent.com/10395907/80049451-8822b600-84d8-11ea-8a21-9a26d6b2c49b.png">

In NEM Wallet, I'm trying to create a new root namespace called "stuff".  

As I try to process this tx in Ledger at first it looks good when I see this. 

<img width="487" alt="image" src="https://user-images.githubusercontent.com/10395907/80049545-cc15bb00-84d8-11ea-8dc5-74dbc475296c.png">

That is good but then I see that Ledger is trying for some reason attach a root namespace that wasn't selected in NEM Wallet. 

<img width="488" alt="image" src="https://user-images.githubusercontent.com/10395907/80049589-f0719780-84d8-11ea-82d6-80c1829abeb4.png">

When this type of error comes up in Ledger, the tx does not go through.

**Comment by TriPhan96** [comment]
I check the creating namespace process many times on both MacOS and Linux and the Ledger Nano S with firmware 1.6.0 and NEM app (version 0.0.1 on Ledger Live), but i haven't gotten this problem yet. Everything works correctly. Could you tell me more details how to reproduce this issue?
But i find that when i create a new namespace, the rental fee is 100 XEM, not 10 XEM like your  mentioned transaction in your [picture.](https://user-images.githubusercontent.com/10395907/80049451-8822b600-84d8-11ea-8a21-9a26d6b2c49b.png)
![image](https://user-images.githubusercontent.com/62920562/80271470-892b3180-86ea-11ea-8cef-394909b414da.png)
And when i create a new sub-namespace, the rental fee is 10 XEM.
![image](https://user-images.githubusercontent.com/62920562/80271514-022a8900-86eb-11ea-9dcc-cddcf55f68e8.png)
So i think this could be a problem with NEM Wallet not a Ledger app's problem.
