### ISSUE TITLE
Change language for mosaics transactions

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/nem-ledger-app#4]
Edit: This issue is meant for NIS1, not Symbol 

<img width="538" alt="image" src="https://user-images.githubusercontent.com/10395907/80049801-7f7eaf80-84d9-11ea-88eb-8bf9d380c000.png">

It currently says "Amount: find 3 mosaics"

It might be better to say "Mosaics: Found 3 txs"

Or maybe somebody can suggest better wordage. 

Also this. 

<img width="551" alt="image" src="https://user-images.githubusercontent.com/10395907/80050087-4b57be80-84da-11ea-942d-1e4a23b5500d.png">

"raw units 1" could say something like "Tx 1 raw units". I think there is just enough space to say that. 

Or again maybe somebody can suggest better wordage.

**Comment by jabo38** [comment]
1: MicroUnits

**Comment by TriPhan96** [comment]
I have updated code for this issue on PR #8
