### ISSUE TITLE
Change hash format

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/nem-ledger-app#5]
Edit: This issue is meant for NIS1, not Symbol 

<img width="841" alt="image" src="https://user-images.githubusercontent.com/10395907/80052085-6aa51a80-84df-11ea-9fb5-ed5b126e9dd6.png">
In the example of a multisig tx, the hash is  27a4b81ada855afd75043736083ab199b2acbb9d3ac476fa8860ef9681c320b9 

And on Ledger it is formatted as  "27a4b8-20b9". 
I think it might be better formatted as "27a4b..20b9"

<img width="605" alt="image" src="https://user-images.githubusercontent.com/10395907/80052218-c96a9400-84df-11ea-85a9-fa86edd3a7a4.png">

**Comment by TriPhan96** [comment]
I have updated the code for this issue on PR #8
